FROM tensorflow/tensorflow:1.14.0-gpu-py3

RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
COPY ./apt_src_aliyun /etc/apt/sources.list

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-get update

RUN apt-get install -y --no-install-recommends git

RUN pip install --upgrade pip
RUN pip install -U setuptools
RUN pip install numpy pandas scikit-learn pyyaml easydict pyperclip keras==2.3.1 h5py==2.10.0 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip install --upgrade "protobuf<=3.20.1" -i https://mirrors.aliyun.com/pypi/simple/

RUN pip install xiangqi minio

RUN git clone https://github.com/splendor-kill/cchess.git /workspace
ENV WORKSPACE /workspace
ENV CODE_DIR $WORKSPACE/src
ENV PYTHONPATH $CODE_DIR
COPY ./src $CODE_DIR
SHELL ["/bin/bash", "-c"]
RUN echo $'#!/bin/bash\n\
PYTHONUNBUFFERED=1 python src/main.py --cmd opt src/config.yaml > opt.log 2>&1 &\
PYTHONUNBUFFERED=1 python src/main.py --cmd eval src/config.yaml > eval.log 2>&1 &\
' > $WORKSPACE/run.sh
RUN chmod +x $WORKSPACE/run.sh
RUN bash -c "mkdir -p $WORKSPACE/logs"
RUN bash -c "mkdir -p $WORKSPACE/data/play_data"
RUN bash -c "mkdir -p $WORKSPACE/data/model/next_generation"
RUN bash -c "mkdir -p $WORKSPACE/model"

#VOLUME  $WORKSPACE/data

WORKDIR $WORKSPACE

ENV TF_FORCE_GPU_ALLOW_GROWTH true

CMD ["./run.sh"]
